<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataIDProviders = array (
  'https://idp.nii.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.nii.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '国立情報学研究所',
    'en' => 
    array (
      'Name' => 'National Institute of Informatics',
    ),
    'ja' => 
    array (
      'Name' => '国立情報学研究所',
    ),
  ),
  'https://shib.itc.nagoya-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://shib.itc.nagoya-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '名古屋大学',
    'en' => 
    array (
      'Name' => 'Nagoya University',
    ),
    'ja' => 
    array (
      'Name' => '名古屋大学',
    ),
  ),
  'https://upki.yamagata-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://upki.yamagata-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '山形大学',
    'en' => 
    array (
      'Name' => 'Yamagata University',
    ),
    'ja' => 
    array (
      'Name' => '山形大学',
    ),
  ),
  'https://upki-idp.chiba-u.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://upki-idp.chiba-u.jp/idp/profile/Shibboleth/SSO',
    'Name' => '千葉大学',
    'en' => 
    array (
      'Name' => 'Chiba University',
    ),
    'ja' => 
    array (
      'Name' => '千葉大学',
    ),
  ),
  'https://authidp1.iimc.kyoto-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://authidp1.iimc.kyoto-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '京都大学',
    'en' => 
    array (
      'Name' => 'Kyoto University',
    ),
    'ja' => 
    array (
      'Name' => '京都大学',
    ),
  ),
  'https://idp.hiroshima-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.hiroshima-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '広島大学',
    'en' => 
    array (
      'Name' => 'Hiroshima University',
    ),
    'ja' => 
    array (
      'Name' => '広島大学',
    ),
  ),
  'https://auth-sso.db.kanazawa-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://auth-sso.db.kanazawa-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '金沢大学',
    'en' => 
    array (
      'Name' => 'Kanazawa University',
    ),
    'ja' => 
    array (
      'Name' => '金沢大学',
    ),
  ),
  'https://shib-idp01.iic.hokudai.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://shib-idp01.iic.hokudai.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '北海道大学',
    'en' => 
    array (
      'Name' => 'Hokkaido University',
    ),
    'ja' => 
    array (
      'Name' => '北海道大学',
    ),
  ),
  'https://idp.account.tsukuba.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.account.tsukuba.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '筑波大学',
    'en' => 
    array (
      'Name' => 'University of Tsukuba',
    ),
    'ja' => 
    array (
      'Name' => '筑波大学',
    ),
  ),
  'https://ssoidp.cc.saga-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://ssoidp.cc.saga-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '佐賀大学',
    'en' => 
    array (
      'Name' => 'Saga University',
    ),
    'ja' => 
    array (
      'Name' => '佐賀大学',
    ),
  ),
  'https://idp.cc.yamaguchi-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.cc.yamaguchi-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '山口大学',
    'en' => 
    array (
      'Name' => 'Yamaguchi University',
    ),
    'ja' => 
    array (
      'Name' => '山口大学',
    ),
  ),
  'https://asura.seijo.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://asura.seijo.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '成城大学',
    'en' => 
    array (
      'Name' => 'Seijo University',
    ),
    'ja' => 
    array (
      'Name' => '成城大学',
    ),
  ),
  'https://upki.toho-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://upki.toho-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '東邦大学',
    'en' => 
    array (
      'Name' => 'Toho University',
    ),
    'ja' => 
    array (
      'Name' => '東邦大学',
    ),
  ),
  'https://fed.mie-u.ac.jp/idp' => 
  array (
    'SSO' => 'https://fed.mie-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '三重大学',
    'en' => 
    array (
      'Name' => 'Mie University',
    ),
    'ja' => 
    array (
      'Name' => '三重大学',
    ),
  ),
  'https://shibboleth.nihon-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://shibboleth.nihon-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '日本大学',
    'en' => 
    array (
      'Name' => 'Nihon University',
    ),
    'ja' => 
    array (
      'Name' => '日本大学',
    ),
  ),
  'https://idp.asahikawa-med.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.asahikawa-med.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '旭川医科大学',
    'en' => 
    array (
      'Name' => 'Asahikawa Medical University',
    ),
    'ja' => 
    array (
      'Name' => '旭川医科大学',
    ),
  ),
  'https://idp2.med.tuat.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp2.med.tuat.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '東京農工大学',
    'en' => 
    array (
      'Name' => 'Tokyo University of Agriculture and Technology',
    ),
    'ja' => 
    array (
      'Name' => '東京農工大学',
    ),
  ),
  'https://odidp.cc.okayama-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://odidp.cc.okayama-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '岡山大学',
    'en' => 
    array (
      'Name' => 'Okayama University',
    ),
    'ja' => 
    array (
      'Name' => '岡山大学',
    ),
  ),
  'https://idp.isc.kyutech.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.isc.kyutech.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '九州工業大学',
    'en' => 
    array (
      'Name' => 'Kyushu Institute of Technology',
    ),
    'ja' => 
    array (
      'Name' => '九州工業大学',
    ),
  ),
  'https://gakunin.kyoto-su.ac.jp/idp' => 
  array (
    'SSO' => 'https://gakunin.kyoto-su.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '京都産業大学',
    'en' => 
    array (
      'Name' => 'Kyoto Sangyo University',
    ),
    'ja' => 
    array (
      'Name' => '京都産業大学',
    ),
  ),
  'https://upki-idp.rikkyo.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://upki-idp.rikkyo.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '立教大学',
    'en' => 
    array (
      'Name' => 'Rikkyo University',
    ),
    'ja' => 
    array (
      'Name' => '立教大学',
    ),
  ),
  'https://idp.kyushu-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.kyushu-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '九州大学',
    'en' => 
    array (
      'Name' => 'Kyushu University',
    ),
    'ja' => 
    array (
      'Name' => '九州大学',
    ),
  ),
  'https://servs.lib.meiji.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://servs.lib.meiji.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '明治大学',
    'en' => 
    array (
      'Name' => 'Meiji University',
    ),
    'ja' => 
    array (
      'Name' => '明治大学',
    ),
  ),
  'https://fed.center.kobe-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://fed.center.kobe-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '神戸大学',
    'en' => 
    array (
      'Name' => 'Kobe University',
    ),
    'ja' => 
    array (
      'Name' => '神戸大学',
    ),
  ),
  'https://idp.gakunin.nii.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.gakunin.nii.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '学認IdP',
    'en' => 
    array (
      'Name' => 'GakuNin IdP',
    ),
    'ja' => 
    array (
      'Name' => '学認IdP',
    ),
  ),
  'https://gakunin.ealps.shinshu-u.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://gakunin.ealps.shinshu-u.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '信州大学',
    'en' => 
    array (
      'Name' => 'Shinshu University',
    ),
    'ja' => 
    array (
      'Name' => '信州大学',
    ),
  ),
  'https://ws1.jichi.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://ws1.jichi.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '自治医科大学',
    'en' => 
    array (
      'Name' => 'Jichi Medical University',
    ),
    'ja' => 
    array (
      'Name' => '自治医科大学',
    ),
  ),
  'https://gknidp.ict.nitech.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://gknidp.ict.nitech.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '名古屋工業大学',
    'en' => 
    array (
      'Name' => 'Nagoya Institute of Technology',
    ),
    'ja' => 
    array (
      'Name' => '名古屋工業大学',
    ),
  ),
  'https://idp.yamanashi.ac.jp/idp/shibboleth' => 
  array (
    'SSO' => 'https://idp.yamanashi.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '山梨大学',
    'en' => 
    array (
      'Name' => 'University of Yamanashi',
    ),
    'ja' => 
    array (
      'Name' => '山梨大学',
    ),
  ),
  'https://fed.ipc.hiroshima-cu.ac.jp/shibboleth-idp' => 
  array (
    'SSO' => 'https://fed.ipc.hiroshima-cu.ac.jp/idp/profile/Shibboleth/SSO',
    'Name' => '広島市立大学',
    'en' => 
    array (
      'Name' => 'Hiroshima City University',
    ),
    'ja' => 
    array (
      'Name' => '広島市立大学',
    ),
  ),
)
?>