<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array (
  'https://scauth.scopus.com/' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://scauth.scopus.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-scauth.scopus.com/SHIRE/SAML/POST',
    ),
  ),
  'https://sdauth.sciencedirect.com/' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://sdauth.sciencedirect.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-sdauth.sciencedirect.com/SHIRE/SAML/POST',
    ),
  ),
  'https://shibboleth.ovid.com/entity' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/POST',
      1 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/Artifact',
      2 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/POST',
      3 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/POST',
      4 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/Artifact',
      5 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/Artifact',
      6 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML2/POST',
    ),
  ),
  'https://downloads.channel8.msdn.com/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://www.dreamspark.com/Shibboleth.sso/SAML/POST',
      5 => 'https://www.dreamspark.com/Shibboleth.sso/SAML/Artifact',
      6 => 'https://www.dreamspark.com/Shibboleth.sso/ADFS',
    ),
  ),
  'https://register-ci.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/auth/action/shibLogin',
    ),
    'ACURL' => 
    array (
      0 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://shibboleth.cambridge.org/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML2/POST',
      1 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML/POST',
    ),
  ),
  'https://www.refworks.com/shibboleth/sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://www.refworks.com/Shibboleth.sso/SAML/POST',
      1 => 'https://www.refworks.com/Shibboleth.sso/SAML/Artifact',
      2 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST',
      3 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST-SimpleSign',
    ),
  ),
  'https://mcu-sp.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://mcu-sp.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer20.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://attrviewer20.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer13.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://attrviewer13.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://hinet-sp.hiroshima-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp1.db.kanazawa-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp2.db.kanazawa-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://fshare.sinet.ad.jp/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://eduroamshib.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://mcus.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://mcus.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://guestog.sso.cc.saga-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp.cc.yamaguchi-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://c.yz.yamagata-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp.tshhosting.com/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.isiknowledge.com/',
      1 => 'https://www.webofknowledge.com/',
    ),
    'ACURL' => 
    array (
      0 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      1 => 'https://www.webofknowledge.com/?auth=Shibboleth',
      2 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      3 => 'https://www.webofknowledge.com/?auth=Shibboleth',
    ),
  ),
  'https://webels.ex.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://reg.huc.hiroshima-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://ninsho-dav.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/DS',
      1 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/DS.reselect',
      2 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/Login',
      3 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/Login.reselect',
    ),
    'ACURL' => 
    array (
      0 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://idp.ixsq.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://www.cc.saga-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer13.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer20.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://office.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/DS',
      1 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/Login',
    ),
    'ACURL' => 
    array (
      0 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'http://shibboleth.ebscohost.com' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML/POST',
    ),
  ),
)
?>