<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array (
  'https://scauth.scopus.com/' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://scauth.scopus.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-scauth.scopus.com/SHIRE/SAML/POST',
    ),
  ),
  'https://sdauth.sciencedirect.com/' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://sdauth.sciencedirect.com/SHIRE/SAML/POST',
      1 => 'https://cdc315-sdauth.sciencedirect.com/SHIRE/SAML/POST',
    ),
  ),
  'https://sp.tshhosting.com/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.isiknowledge.com/',
      1 => 'https://www.webofknowledge.com/',
    ),
    'ACURL' => 
    array (
      0 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      1 => 'https://www.webofknowledge.com/?auth=Shibboleth',
      2 => 'https://www.isiknowledge.com/?auth=Shibboleth',
      3 => 'https://www.webofknowledge.com/?auth=Shibboleth',
    ),
  ),
  'https://shibboleth.ovid.com/entity' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/POST',
      1 => 'https://shibboleth-dev.ovid.com:8085/Shibboleth.sso/SAML/Artifact',
      2 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/POST',
      3 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/POST',
      4 => 'https://shib-qa.ovid.com/Shibboleth.sso/SAML/Artifact',
      5 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML/Artifact',
      6 => 'https://shibboleth.ovid.com/Shibboleth.sso/SAML2/POST',
    ),
  ),
  'http://shibboleth.metapress.com/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML/POST',
      5 => 'https://shibboleth.metapress.com/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://downloads.channel8.msdn.com/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.dreamspark.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://www.dreamspark.com/Shibboleth.sso/SAML/POST',
      5 => 'https://www.dreamspark.com/Shibboleth.sso/SAML/Artifact',
      6 => 'https://www.dreamspark.com/Shibboleth.sso/ADFS',
    ),
  ),
  'https://register-ci.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/auth/action/shibLogin',
    ),
    'ACURL' => 
    array (
      0 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML2/ECP',
      4 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML/POST',
      5 => 'https://register-ci.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://shibboleth.cambridge.org/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML2/POST',
      1 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML/POST',
      2 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML2/POST-SimpleSign',
      3 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML2/Artifact',
      4 => 'https://shibboleth.cambridge.org/Shibboleth.sso/SAML2/ECP',
    ),
  ),
  'https://www.refworks.com/shibboleth/sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://www.refworks.com/Shibboleth.sso/SAML/POST',
      1 => 'https://www.refworks.com/Shibboleth.sso/SAML/Artifact',
      2 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST',
      3 => 'https://www.refworks.com/Shibboleth.sso/SAML2/POST-SimpleSign',
    ),
  ),
  'https://atlases.muni.cz/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://atlases.muni.cz/Shibboleth.sso/WAYF/eduid',
      1 => 'https://atlases.muni.cz/Shibboleth.sso/DS',
      2 => 'https://atlases.muni.cz/Shibboleth.sso/DS/eduid',
      3 => 'https://atlases.muni.cz/Shibboleth.sso/DS/dfnaai',
      4 => 'https://atlases.muni.cz/Shibboleth.sso/surf',
      5 => 'https://atlases.muni.cz/Shibboleth.sso/niif',
      6 => 'https://atlases.muni.cz/Shibboleth.sso/upki',
      7 => 'https://atlases.muni.cz/Shibboleth.sso/chimarrao',
      8 => 'https://atlases.muni.cz/Shibboleth.sso/aaf',
      9 => 'https://atlases.muni.cz/Shibboleth.sso/pionier',
      10 => 'https://atlases.muni.cz/Shibboleth.sso/kalmar',
      11 => 'https://atlases.muni.cz/Shibboleth.sso/arnes',
      12 => 'https://atlases.muni.cz/Shibboleth.sso/switch',
    ),
    'ACURL' => 
    array (
      0 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/POST',
      1 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://atlases.muni.cz/Shibboleth.sso/SAML2/ECP',
      4 => 'https://atlases.muni.cz/Shibboleth.sso/SAML/POST',
      5 => 'https://atlases.muni.cz/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://hinet-sp.hiroshima-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://hinet-sp.hiroshima-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp1.db.kanazawa-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp1.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp2.db.kanazawa-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp2.db.kanazawa-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://fshare.sinet.ad.jp/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://fshare.sinet.ad.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://eduroamshib.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://eduroamshib.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://mcus.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://mcus.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://mcus.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://guestog.sso.cc.saga-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://guestog.sso.cc.saga-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp.cc.yamaguchi-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://sp.cc.yamaguchi-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://c.yz.yamagata-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://c.yz.yamagata-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://webels.ex.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://webels.ex.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://reg.huc.hiroshima-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://reg.huc.hiroshima-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://ninsho-dav.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/DS',
      1 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/DS.reselect',
      2 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/Login',
      3 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/Login.reselect',
    ),
    'ACURL' => 
    array (
      0 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://ninsho-dav.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://www.pieronline.jp/shibboleth' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://www.pieronline.jp/session/shib',
      1 => 'https://www.pieronline.jp/session/shib',
    ),
  ),
  'https://idp.ixsq.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://idp.ixsq.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://www.cc.saga-u.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://www.cc.saga-u.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer13.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      1 => 'https://attrviewer13.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://attrviewer20.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://attrviewer20.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://office.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/DS',
      1 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/Login',
    ),
    'ACURL' => 
    array (
      0 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://office.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'http://shibboleth.ebscohost.com' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://shibboleth.ebscohost.com/Shibboleth.sso/SAML/POST',
    ),
  ),
  'https://gakusp01.kyoto-su.ac.jp/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML2/ECP',
      4 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML/POST',
      5 => 'https://gakusp01.kyoto-su.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://auth.cs.serialssolutions.com/auth/Metadata/Shib' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://login.serialssolutions.com/sso/auth/CS/rcv/saml1',
      1 => 'https://login.serialssolutions.com/sso/auth/CS/rcv/saml1',
    ),
  ),
  'https://auth.search.serialssolutions.com/auth/Metadata/Shib' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://login.serialssolutions.com/sso/auth/LINK/rcv/saml1',
      1 => 'https://login.serialssolutions.com/sso/auth/LINK/rcv/saml1',
    ),
  ),
  'https://el.consortium.or.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://el.consortium.or.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://el.consortium.or.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://el.consortium.or.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://el.consortium.or.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://el.consortium.or.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://el.consortium.or.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://sp.ebrary.com/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://sp.ebrary.com/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://sp.ebrary.com/Shibboleth.sso/SAML/POST',
      1 => 'https://sp.ebrary.com/Shibboleth.sso/SAML/Artifact',
      2 => 'https://sp.ebrary.com/Shibboleth.sso/SAML2/POST',
      3 => 'https://sp.ebrary.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      4 => 'https://sp.ebrary.com/Shibboleth.sso/SAML2/Artifact',
      5 => 'https://sp.ebrary.com/Shibboleth.sso/SAML2/ECP',
    ),
  ),
  'http://reo.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'http://reo.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'http://reo.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'http://reo.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'http://reo.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'http://reo.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'http://reo.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://ieeexplore.ieee.org/shibboleth-sp' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST',
      1 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://ieeexplore.ieee.org/Shibboleth/Shibboleth.sso/SAML/POST',
    ),
  ),
  'https://service.ecloud.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://service.ecloud.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://kod.kenkyusha.co.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://kod.kenkyusha.co.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://foodl.org/simplesaml/module.php/saml/sp/metadata.php/saml' => 
  array (
    'ACURL' => 
    array (
      0 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml2-acs.php/saml',
      1 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml1-acs.php/saml',
      2 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml2-acs.php/saml',
      3 => 'https://foodl.org/simplesaml/module.php/saml/sp/saml1-acs.php/saml/artifact',
    ),
  ),
  'https://gmembers.sinet.ad.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/Login',
    ),
    'ACURL' => 
    array (
      0 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://gmembers.sinet.ad.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://map.gakunin.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/Login',
      1 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://map.gakunin.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://meatwiki.nii.ac.jp/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://meatwiki.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://openid.nii.ac.jp/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://openid.nii.ac.jp/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://openid.nii.ac.jp/Shibboleth.sso/SAML2/POST',
      1 => 'https://openid.nii.ac.jp/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://openid.nii.ac.jp/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://openid.nii.ac.jp/Shibboleth.sso/SAML/POST',
      4 => 'https://openid.nii.ac.jp/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://shibosuke.net/shibboleth-sp' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://shibosuke.net/Shibboleth.sso/DS',
    ),
    'ACURL' => 
    array (
      0 => 'https://shibosuke.net/Shibboleth.sso/SAML2/POST',
      1 => 'https://shibosuke.net/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://shibosuke.net/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://shibosuke.net/Shibboleth.sso/SAML/POST',
      4 => 'https://shibosuke.net/Shibboleth.sso/SAML/Artifact',
    ),
  ),
  'https://content.karger.com/shibboleth' => 
  array (
    'DSURL' => 
    array (
      0 => 'https://content.karger.com/Shibboleth.sso/DS',
      1 => 'https://content.karger.com/Shibboleth.sso/dfn-aai',
      2 => 'https://content.karger.com/Shibboleth.sso/gakunin-japan',
    ),
    'ACURL' => 
    array (
      0 => 'https://content.karger.com/Shibboleth.sso/SAML2/POST',
      1 => 'https://content.karger.com/Shibboleth.sso/SAML2/POST-SimpleSign',
      2 => 'https://content.karger.com/Shibboleth.sso/SAML2/Artifact',
      3 => 'https://content.karger.com/Shibboleth.sso/SAML2/ECP',
      4 => 'https://content.karger.com/Shibboleth.sso/SAML/POST',
      5 => 'https://content.karger.com/Shibboleth.sso/SAML/Artifact',
    ),
  ),
)
?>